### ISSUE TITLE
tags.tiqcdn.com in category-ads-all breaks webpages

### ISSUE THREAD

**Issue by mmrabbani** [v2fly/domain-list-community#1687]
Hello
When I block "category-ads-all", some webpage in intel and some other websites breaks. The reason is after blocking this list, "tags.tiqcdn.com" is blocked that have non-ad function. The problem is: I cannot find "tags.tiqcdn.com" in "category-ads-all" and I don't know why this list mentions this domain.
When I unblock "category-ads-all", "tags.tiqcdn.com" is not blocked anymore. Even blocking "category-ads" doesn't have this problem.
If I had found "tags.tiqcdn.com" or "tiqcdn.com" this list, I would have deleted it in a pull request.
You can test yourself about blocking this domain.

**Comment by IceCodeNew** [comment]
<img width="379" alt="image" src="https://github.com/v2fly/domain-list-community/assets/32576256/47965cef-bd00-4a8c-9b78-6238d68ea10b">

The `tiqcdn.com` does not exist in both https://github.com/v2fly/domain-list-community & https://github.com/Loyalsoldier/v2ray-rules-dat/tree/hidden . I assume the problem is due to a third-party project that I am not familiar with.
Sorry about that. There is nothing I can do to help you.
